export MainContainer from './Main/MainContainer';
export HomeContainer from './Home/HomeContainer';
export AuthenticateContainer from './Authenticate/AuthenticateContainer'
export FeedContainer from './Feed/FeedContainer'
export LogoutContainer from './Logout/LogoutContainer'
export ModalContainer from './Modal/ModalContainer'
export DuckContainer from './Question/QuestionContainer'
export UserContainer from './User/UserContainer'
export DuckDetailsContainer from './QuestionDetails/QuestionDetailsContainer'
export RepliesContainer from './Replies/RepliesContainer'
export ConfirmRegistrationContainer from './ConfirmRegistration/ConfirmRegistrationContainer'